# -1だと最大リソースを使用
max_workers: -1

# 作成したデータセットの出力先
output_dir: E:\ReinVisionOCR\coatnet\dataset

# フォントパスとサイズ
font_path: E:\ReinVisionOCR\resources\fonts\msgothic\msgothic001.ttf
font_size: [23, 25, 27, 29]

# 文字位置
text_pos_pattern_list: [-2, -1, 0, 1, 2]

# リサイズ
resize: [32, 32]

# 生成数
n_valid: 5

# 除外文字
# 各リストの先頭文字のみを生成、以降は生成しないことで不適切な精度劣化を防止
ignore_code_list: [
  # カタカナのろ
  # 漢字のくち
  # 漢字のくに、かこむ
  ["ロ", "口", "囗"],

  # 長音符
  # 漢字のいち
  ["ー", "一"],

  # カタカナのか
  # 漢字のちから
  ["カ", "力"],
  
  # カタカナのに
  # 漢字のに
  ["ニ", "二"],

  # カタカナのえ
  # 漢字のこう
  ["エ", "工"],

  # 小文字の全角英字Ｌ
  # 漢字の丨部（こんぶ）
  ["ｌ", "丨"],

  # ひらがなのへ
  # カタカナのへ
  ["へ", "ヘ"],

  # カタカナのと
  # 漢字のぼく、と、うらない
  ["ト", "卜"],

  # ひらがなのべ
  # カタカナのべ
  ["べ", "ベ"],

  # カタカナのむ
  # 漢字の厶部（しぶ）
  ["ム", "厶"],

  # 全角数字の０
  # 大文字の全角英字Ｏ
  ["０", "Ｏ"],

  # 囲い文字の」
  # 漢字の亅部（けつぶ）
  ["」", "亅"],
]

# 生成文字
code_params: [
  # ひらがな
  [12353, 12438],
  # カタカナ
  [12449, 12540],
  # 数字
  [65296, 65305],
  # 英字（大文字）
  [65, 90],
  # 英字（小文字）
  [97, 122],
  # 記号
  [＄￥＋＠；：％＆＝’‘／！？「」【】『』［］、。…※＊＜＞（）＃“”～♪],
  # 記号みたいな数字
  [①②③④⑤⑥⑦⑧⑨],
  # テキストに含まれた文字列を生成
  [E:\ReinVisionOCR\resources\jpn.txt],
]
